package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 客户基本信息里面的科技项目列表
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmTechnologyProject<M extends BaseCrmTechnologyProject<M>> extends Model<M> implements IBean {

	public void setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("project_id");
	}

	public void setSolrId(java.lang.String solrId) {
		set("solr_id", solrId);
	}
	
	public java.lang.String getSolrId() {
		return getStr("solr_id");
	}

	public void setCustomerId(java.lang.Integer customerId) {
		set("customer_id", customerId);
	}
	
	public java.lang.Integer getCustomerId() {
		return getInt("customer_id");
	}

	public void setProjectName(java.lang.String projectName) {
		set("project_name", projectName);
	}
	
	public java.lang.String getProjectName() {
		return getStr("project_name");
	}

	public void setApplyDate(java.lang.String applyDate) {
		set("apply_date", applyDate);
	}
	
	public java.lang.String getApplyDate() {
		return getStr("apply_date");
	}

	public void setFileNames(java.lang.String fileNames) {
		set("file_names", fileNames);
	}
	
	public java.lang.String getFileNames() {
		return getStr("file_names");
	}

	public void setFileUrls(java.lang.String fileUrls) {
		set("file_urls", fileUrls);
	}
	
	public java.lang.String getFileUrls() {
		return getStr("file_urls");
	}

}
