package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 客户的财税相关信息
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmTax<M extends BaseCrmTax<M>> extends Model<M> implements IBean {

	public void setTaxId(java.lang.Integer taxId) {
		set("tax_id", taxId);
	}
	
	public java.lang.Integer getTaxId() {
		return getInt("tax_id");
	}

	public void setSolrId(java.lang.String solrId) {
		set("solr_id", solrId);
	}
	
	public java.lang.String getSolrId() {
		return getStr("solr_id");
	}

	public void setCustomerId(java.lang.Integer customerId) {
		set("customer_id", customerId);
	}
	
	public java.lang.Integer getCustomerId() {
		return getInt("customer_id");
	}

	public void setYear(java.lang.String year) {
		set("year", year);
	}
	
	public java.lang.String getYear() {
		return getStr("year");
	}

	public void setTotalProperty(java.math.BigDecimal totalProperty) {
		set("total_property", totalProperty);
	}
	
	public java.math.BigDecimal getTotalProperty() {
		return get("total_property");
	}

	public void setTotalBusinessIncome(java.math.BigDecimal totalBusinessIncome) {
		set("total_business_income", totalBusinessIncome);
	}
	
	public java.math.BigDecimal getTotalBusinessIncome() {
		return get("total_business_income");
	}

	public void setTotalProfits(java.math.BigDecimal totalProfits) {
		set("total_profits", totalProfits);
	}
	
	public java.math.BigDecimal getTotalProfits() {
		return get("total_profits");
	}

	public void setRetainedProfits(java.math.BigDecimal retainedProfits) {
		set("retained_profits", retainedProfits);
	}
	
	public java.math.BigDecimal getRetainedProfits() {
		return get("retained_profits");
	}

	public void setTotalTax(java.math.BigDecimal totalTax) {
		set("total_tax", totalTax);
	}
	
	public java.math.BigDecimal getTotalTax() {
		return get("total_tax");
	}

	public void setTotalLiabilities(java.math.BigDecimal totalLiabilities) {
		set("total_liabilities", totalLiabilities);
	}
	
	public java.math.BigDecimal getTotalLiabilities() {
		return get("total_liabilities");
	}

	public void setTotalResearchFee(java.math.BigDecimal totalResearchFee) {
		set("total_research_fee", totalResearchFee);
	}
	
	public java.math.BigDecimal getTotalResearchFee() {
		return get("total_research_fee");
	}

	public void setTotalResearchPeoples(java.lang.Integer totalResearchPeoples) {
		set("total_research_peoples", totalResearchPeoples);
	}
	
	public java.lang.Integer getTotalResearchPeoples() {
		return getInt("total_research_peoples");
	}

	public void setTotalCollegeDegree(java.lang.Integer totalCollegeDegree) {
		set("total_college_degree", totalCollegeDegree);
	}
	
	public java.lang.Integer getTotalCollegeDegree() {
		return getInt("total_college_degree");
	}

}
