package com.kakarote.crm9.erp.work.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTemplateDocument<M extends BaseTemplateDocument<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	public Integer getId() {
		return getInt("id");
	}

	public void setTemplateId(Integer templateId) {
		set("template_id", templateId);
	}
	public Integer getTemplateId() {
		return getInt("template_id");
	}

	public void setDocumentId(Integer documentId) {
		set("document_id", documentId);
	}
	public Integer getDocumentId() {
		return getInt("document_id");
	}


}
