package com.kakarote.crm9.erp.work.entity;

import com.kakarote.crm9.erp.work.entity.base.BaseTemplateDocument;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TemplateDocument extends BaseTemplateDocument<TemplateDocument> {
	public static final TemplateDocument dao = new TemplateDocument().dao();
}
