package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmTax;

/**
 * 客户的财税相关信息
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmTax extends BaseCrmTax<CrmTax> {
	public static final CrmTax dao = new CrmTax().dao();
}
