package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmTechnologyProject;

/**
 * 客户基本信息里面的科技项目列表
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmTechnologyProject extends BaseCrmTechnologyProject<CrmTechnologyProject> {
	public static final CrmTechnologyProject dao = new CrmTechnologyProject().dao();
}
